import{a as w,S,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(o){if(o.ep)return;o.ep=!0;const i=t(o);fetch(o.href,i)}})();const q="50196951-391601c250e619b024764c208",R="https://pixabay.com/api/";async function g(e,r){const t={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await w.get(R,{params:t})).data}catch(s){throw console.error("Помилка під час запиту до Pixabay API:",s),s}}const y=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more-button"),I=new S(".gallery a",{captionsData:"alt",captionDelay:250});function M({webformatURL:e,largeImageURL:r,tags:t,likes:s,views:o,comments:i,downloads:a}){return`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${e}" alt="${t}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${s}</p>
        <p class="info-item"><b>Views</b> ${o}</p>
        <p class="info-item"><b>Comments</b> ${i}</p>
        <p class="info-item"><b>Downloads</b> ${a}</p>
      </div>
    </li>
  `}function b(e){if(!e||e.length===0)return;const r=e.map(t=>M(t)).join("");y.insertAdjacentHTML("beforeend",r),I.refresh()}function P(){y.innerHTML=""}function L(){u&&u.classList.add("visible")}function v(){u&&u.classList.remove("visible")}function p(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}function B(){const e=y.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}const m=document.querySelector(".form"),$=m.querySelector('input[name="search-text"]'),E=document.querySelector(".load-more-button");let h="",c=1;const H=15;let l=0;f();m.addEventListener("submit",async e=>{e.preventDefault();const r=$.value.trim();if(r===""){n.warning({title:"Увага",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}h=r,c=1,l=0,P(),f(),L();try{const t=await g(h,c);t.hits.length===0?n.info({title:"Інформація",message:"На жаль, зображень за вашим запитом не знайдено. Спробуйте ще раз!",position:"topRight"}):(b(t.hits),l=t.totalHits,t.hits.length<l?p():n.info({title:"Інформація",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"}),console.error("Помилка пошуку:",t)}finally{v(),m.reset()}});E.addEventListener("click",async()=>{c+=1,L(),f();try{const e=await g(h,c);b(e.hits),c*H<l?p():(f(),n.info({title:"Інформація",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const t=B();t>0&&window.scrollBy({top:t*2,behavior:"smooth"})}catch(e){n.error({title:"Помилка",message:"Не вдалося завантажити додаткові зображення. Спробуйте пізніше.",position:"topRight"}),console.error("Помилка завантаження додаткових зображень:",e),p()}finally{v()}});
//# sourceMappingURL=index.js.map
